//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Dip.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_DLG_Intensity               102
#define IDD_DLG_LinerPara               103
#define IDD_DLG_PointStre               104
#define IDD_DLG_THRESHOLD               105
#define IDD_DLG_Smooth                  106
#define IDD_DLG_Color                   108
#define IDD_DLG_EdgeDet                 109
#define IDD_DLG_LaplacianDet            110
#define IDD_CHANNEL_COMBINE             113
#define IDD_DLG_MedianFilter            114
#define IDD_DLG_GEORota                 115
#define IDD_DLG_GEOTrans                116
#define IDD_DLG_GEOZoom                 117
#define IDD_DLG_Fourior_Filter          118
#define IDD_DLG_MORPH                   119
#define IDD_DLG_HitMiss                 120
#define IDD_DLG_FEATURE                 121
#define IDD_DLG_Huffman                 122
#define IDD_DLG_Shannon                 123
#define IDD_DLG_STRINPUT                124
#define IDR_MAINFRAME                   128
#define IDR_DIPTYPE                     129
#define IDD_DLG_SEEDFILL                132
#define IDD_DLG_PROJECT                 133
#define IDS_SPLIT_RED_CAPTION           139
#define IDS_SPLIT_GREEN_CAPTION         140
#define IDS_SPLIT_BLUE_CAPTION          141
#define IDS_FAIL_SPLIT                  154
#define IDI_LEDON                       160
#define IDI_LEDOFF                      161
#define IDI_MIDON                       162
#define IDI_MIDOFF                      163
#define IDI_HITMISS_MID                 164
#define IDI_HITMISS_LED                 165
#define IDC_RAD8                        1000
#define IDC_EDIT_XOffset                1000
#define IDC_HISTOGRAMTYPE               1001
#define IDC_EDIT_TEMPC_SPIN             1001
#define IDC_EDIT_YOffset                1001
#define IDC_RED_RADIO                   1002
#define IDC_RAD4                        1002
#define IDC_EDIT_XZoom                  1002
#define IDC_GREEN_RADIO                 1003
#define IDC_DIRECTION0                  1003
#define IDC_EDIT_YZoom                  1003
#define IDC_BLUE_RADIO                  1004
#define IDC_DIRECTION2                  1004
#define IDC_EDIT_Rotate                 1004
#define IDC_EDIT_STRU_H                 1004
#define IDC_IDC_EDIT_LOWSPIN            1005
#define IDC_RAD1                        1005
#define IDC_EDIT_STRU_W                 1005
#define IDC_IDC_EDIT_UPSPIN             1006
#define IDC_RAD2                        1006
#define IDC_EDIT_STRU_XC                1006
#define IDC_TRESHOLD_WHITE              1007
#define IDC_RAD3                        1007
#define IDC_EDIT_STRU_YC                1007
#define IDC_IDC_EDIT_CURSPIN            1008
#define IDC_DIRECTION4                  1008
#define IDC_EDIT_STRU_H_SPIN            1008
#define IDC_TRESHOLD_BLACK              1009
#define IDC_EDIT_TEMPH_SPIN             1009
#define IDC_THRESH_METHOD1              1010
#define IDC_EDIT_TEMPH                  1010
#define IDC_EDIT_A                      1011
#define IDC_THRESH_METHOD2              1011
#define IDC_EDIT_TEMPW                  1011
#define IDC_EDIT_B                      1012
#define IDC_THRESH_METHOD3              1012
#define IDC_EDIT_V0                     1012
#define IDC_COORD                       1013
#define IDC_EDIT_V1                     1013
#define IDC_EDIT_CUR_TRESHOLD           1014
#define IDC_EDIT_V2                     1014
#define IDC_EDIT_CUR_TRESHSPIN          1015
#define IDC_EDIT_V3                     1015
#define IDC_EDIT_LowGray                1016
#define IDC_EDIT_V4                     1016
#define IDC_EDIT_UpGray                 1017
#define IDC_EDIT_V5                     1017
#define IDC_EDIT_CUR_NUMBER             1018
#define IDC_EDIT_X1                     1018
#define IDC_EDIT_UPSPIN                 1018
#define IDC_EDIT_V6                     1018
#define IDC_EDIT_CUR_GRAY               1019
#define IDC_EDIT_Y1                     1019
#define IDC_EDIT_LOWSPIN                1019
#define IDC_EDIT_V7                     1019
#define IDC_EDIT_X2                     1020
#define IDC_STATIC_CURTHRESH            1020
#define IDC_EDIT_V8                     1020
#define IDC_EDIT_Y2                     1021
#define IDC_EDIT_V9                     1021
#define IDC_COLOR_LIST                  1021
#define IDC_EDIT_V10                    1022
#define IDC_LST_Table                   1022
#define IDC_EDIT_V11                    1023
#define IDC_STATIC1                     1023
#define IDC_EDIT_V12                    1024
#define IDC_STATIC2                     1024
#define IDC_EDIT_V13                    1025
#define IDC_STATIC3                     1025
#define IDC_EDIT_V14                    1026
#define IDC_EDIT_ENTROPY                1026
#define IDC_EDIT_V15                    1027
#define IDC_XSPIN                       1027
#define IDC_EDIT_CODELEN                1027
#define IDC_EDIT_V16                    1028
#define IDC_YSPIN                       1028
#define IDC_EDIT_CODEEF                 1028
#define IDC_EDIT_V17                    1029
#define IDC_TRANS_TYPE                  1029
#define IDC_EDIT_V18                    1030
#define IDC_RADIO2                      1030
#define IDC_EDIT_V19                    1031
#define IDC_INTORTYPE                   1031
#define IDC_EDIT_V20                    1032
#define IDC_Freq_Fitler_a               1032
#define IDC_EDIT_V21                    1033
#define IDC_EDIT_V22                    1034
#define IDC_Filter_TYPE                 1034
#define IDC_EDIT_V23                    1035
#define IDC_EDIT_V24                    1036
#define IDC_RAD5                        1037
#define IDC_EDIT_TEMPC                  1038
#define IDC_EDIT_MX                     1039
#define IDC_EDIT_MY                     1040
#define IDC_EDIT_TEMPW_SPIN             1041
#define IDC_DIAMOND                     1041
#define IDC_EDIT_MX_SPIN                1042
#define IDC_SQUARE                      1042
#define IDC_EDIT_MY_SPIN                1043
#define IDC_CUSTOM                      1043
#define IDC_RAD6                        1044
#define IDC_RAD7                        1045
#define IDC_DIRECTION6                  1045
#define IDC_DIRECTION1                  1046
#define IDC_DIRECTION3                  1047
#define IDC_DIRECTION5                  1048
#define IDC_DIRECTION7                  1049
#define IDC_RADIO_SEEDFILL1             1050
#define IDC_RADIO_SEEDFILL2             1051
#define IDC_STRU00                      1052
#define IDC_RADIO_PROJECTH              1052
#define IDC_STRU01                      1053
#define IDC_RADIO_PROJECTV              1053
#define IDC_STRU02                      1054
#define IDC_STRU03                      1055
#define IDC_STRU04                      1056
#define IDC_STRU05                      1057
#define IDC_STRU06                      1058
#define IDC_STRU07                      1059
#define IDC_STRU08                      1060
#define IDC_STRU09                      1061
#define IDC_STRU10                      1062
#define IDC_STRU11                      1063
#define IDC_STRU12                      1064
#define IDC_STRU13                      1065
#define IDC_STRU14                      1066
#define IDC_STRU15                      1067
#define IDC_STRU16                      1068
#define IDC_STRU17                      1069
#define IDC_STRU18                      1070
#define IDC_STRU19                      1071
#define IDC_STRU20                      1072
#define IDC_STRU21                      1073
#define IDC_STRU22                      1074
#define IDC_STRU23                      1075
#define IDC_STRU24                      1076
#define IDC_CIRCLE                      1077
#define IDC_RADIO_GRAY                  1077
#define IDC_EDIT_STRINPUT               1077
#define IDC_SORT1                       1078
#define IDC_RECT                        1078
#define IDC_RADIO_GREEN                 1078
#define IDC_SORT2                       1079
#define IDC_HORI                        1079
#define IDC_RADIO_BLUE                  1079
#define IDC_VERT                        1080
#define IDC_RADIO_RED                   1080
#define IDC_EDIT_XSCALE                 1081
#define IDC_EDIT_YSCALE                 1082
#define IDC_EDIT_STRU_W_SPIN            1083
#define IDC_EDIT_XYSCALE                1083
#define IDC_EDIT_CENTROID               1084
#define IDC_EDIT_STRU_XC_SPIN           1086
#define IDC_RADIO_CUSTOM                1086
#define IDC_EDIT_STRU_YC_SPIN           1087
#define IDC_RADIO_RECALIB               1087
#define IDC_EDIT_PERIMETER              1088
#define IDC_EDIT_AREA                   1089
#define IDC_EDIT_COMPACT                1090
#define IDC_STATIC_FOURIER              1093
#define IDC_CHECK_RETAIN                1094
#define IDC_RED_CHANNEL                 1164
#define IDC_GREEN_CHANNEL               1165
#define IDC_BLUE_CHANNEL                1166
#define ID_VIEW_HIST                    32771
#define ID_GEOM_ROTA                    32772
#define ID_POINT_GRAY_RED               32774
#define ID_POINT_GRAY_GREEN             32775
#define ID_POINT_GRAY_BLUE              32776
#define ID_POINT_GRAY_MIXED             32777
#define ID_POINT_CONTAUTO               32778
#define ID_GEOM_MIRV2                   32779
#define ID_GEOM_MIRH2                   32780
#define ID_GEOM_TRPO2                   32781
#define ID_GEOM_ZOOM2                   32782
#define ID_POINT_STRE                   32783
#define ID_POINT_EQUA                   32784
#define ID_ANALYSE_FEATURE              32785
#define ID_POINT_INVERT                 32786
#define ID_POINT_LINER                  32787
#define ID_ENHA_SMOOTH                  32788
#define ID_POINT_THRE                   32789
#define ID_POINT_PSEUDOCOLOR            32790
#define ID_FREQ_DCT                     32792
#define ID_FREQ_WALH                    32793
#define ID_FREQ_FFT                     32795
#define ID_CODE_HUFFMAN                 32796
#define ID_FREQ_NFFT                    32797
#define ID_CODE_SHANNON                 32803
#define ID_MORPH_EROSION                32804
#define ID_MORPH_DILATION               32805
#define ID_MORPH_OPEN                   32806
#define ID_MORPH_CLOSE                  32807
#define ID_MORPH_THINING                32808
#define ID_FREQ_FFT_FILTE               32814
#define ID_ANALYSE_LABEL                32815
#define ID_ENHA_MidianF                 32816
#define ID_ANALYSE_TRACE                32817
#define ID_ENHA_GRADSHARP               32818
#define ID_ENHA_LAPSHARP                32819
#define ID_ENHA_TEMPSHARP               32820
#define ID_CHANNEL_SPLIT                32821
#define ID_CHANNEL_COMBINE              32822
#define ID_CHANNEL_MIXED                32823
#define ID_CHANNEL_RED                  32824
#define ID_CHANNEL_GREEN                32825
#define ID_CHANNEL_BLUE                 32826
#define ID_GEOM_MIRV                    32827
#define ID_GEOM_TRAN                    32828
#define ID_GEOM_MIRH                    32829
#define ID_GEOM_TRPO                    32830
#define ID_GEOM_ZOOM                    32831
#define ID_FREQ_NDCT                    32832
#define ID_FREQ_NWALH                   32833
#define ID_MORPH_HITMISSING             32834
#define ID_CODE_ARITH                   32835
#define ID_DETECT_PROJECT               32836
#define ID_DETECT_MINUS                 32837
#define ID_DETECT_TEMPLATE              32838
#define ID_EDGE_CONTOUR                 32839
#define ID_EDGE_FILL                    32840
#define ID_EDGE_TRACE                   32841
#define IDS_FAIL_COMBINE                61447
#define IDS_COMBINE_CAPTION             61448
#define IDS_SPLIT_MIXED_CAPTION         61449

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32836
#define _APS_NEXT_CONTROL_VALUE         1083
#define _APS_NEXT_SYMED_VALUE           125
#endif
#endif
